### ISSUE TITLE
Keyboard buttons replacement

### ISSUE THREAD

**Issue by matopysny** [unfoldcollective/Apprentice-of-Okolicne#40] opened 2017-08-23 13:05 UTC
Please replace signs "SPACE" and "DEL" by these svgs.

https://drive.google.com/drive/folders/0B0LkX_BiOf9xT3ExOW55MnRldjA

**Comment by phivk** [comment] 2017-08-23 13:15
Duplicate of #32 , closing this issue

**Closed as completed by phivk** 2017-08-23 13:15 UTC
